// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: exchange/v1/authz.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// CreateSpotLimitOrderAuthz defines authorization for creating spot limit orders
// Restrictsto specific markets and subaccounts
type CreateSpotLimitOrderAuthz struct {
	// subaccount_id restricts to specific subaccount (empty = any subaccount)
	SubaccountId string `protobuf:"bytes,1,opt,name=subaccount_id,json=subaccountId,proto3" json:"subaccount_id,omitempty"`
	// market_ids restricts to specific markets (empty = all markets)
	MarketIds []string `protobuf:"bytes,2,rep,name=market_ids,json=marketIds,proto3" json:"market_ids,omitempty"`
	// max_order_value is the maximum value per order (0 = unlimited)
	MaxOrderValue types.Coin `protobuf:"bytes,3,opt,name=max_order_value,json=maxOrderValue,proto3" json:"max_order_value"`
}

func (m *CreateSpotLimitOrderAuthz) Reset()         { *m = CreateSpotLimitOrderAuthz{} }
func (m *CreateSpotLimitOrderAuthz) String() string { return proto.CompactTextString(m) }
func (*CreateSpotLimitOrderAuthz) ProtoMessage()    {}
func (*CreateSpotLimitOrderAuthz) Descriptor() ([]byte, []int) {
	return fileDescriptor_1520d02852beec97, []int{0}
}
func (m *CreateSpotLimitOrderAuthz) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CreateSpotLimitOrderAuthz) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CreateSpotLimitOrderAuthz.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CreateSpotLimitOrderAuthz) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSpotLimitOrderAuthz.Merge(m, src)
}
func (m *CreateSpotLimitOrderAuthz) XXX_Size() int {
	return m.Size()
}
func (m *CreateSpotLimitOrderAuthz) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSpotLimitOrderAuthz.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSpotLimitOrderAuthz proto.InternalMessageInfo

func (m *CreateSpotLimitOrderAuthz) GetSubaccountId() string {
	if m != nil {
		return m.SubaccountId
	}
	return ""
}

func (m *CreateSpotLimitOrderAuthz) GetMarketIds() []string {
	if m != nil {
		return m.MarketIds
	}
	return nil
}

func (m *CreateSpotLimitOrderAuthz) GetMaxOrderValue() types.Coin {
	if m != nil {
		return m.MaxOrderValue
	}
	return types.Coin{}
}

// CreateSpotMarketOrderAuthz defines authorization for creating spot market orders
type CreateSpotMarketOrderAuthz struct {
	// subaccount_id restricts to specific subaccount (empty = any subaccount)
	SubaccountId string `protobuf:"bytes,1,opt,name=subaccount_id,json=subaccountId,proto3" json:"subaccount_id,omitempty"`
	// market_ids restricts to specific markets (empty = all markets)
	MarketIds []string `protobuf:"bytes,2,rep,name=market_ids,json=marketIds,proto3" json:"market_ids,omitempty"`
	// max_order_value is the maximum value per order (0 = unlimited)
	MaxOrderValue types.Coin `protobuf:"bytes,3,opt,name=max_order_value,json=maxOrderValue,proto3" json:"max_order_value"`
}

func (m *CreateSpotMarketOrderAuthz) Reset()         { *m = CreateSpotMarketOrderAuthz{} }
func (m *CreateSpotMarketOrderAuthz) String() string { return proto.CompactTextString(m) }
func (*CreateSpotMarketOrderAuthz) ProtoMessage()    {}
func (*CreateSpotMarketOrderAuthz) Descriptor() ([]byte, []int) {
	return fileDescriptor_1520d02852beec97, []int{1}
}
func (m *CreateSpotMarketOrderAuthz) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CreateSpotMarketOrderAuthz) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CreateSpotMarketOrderAuthz.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CreateSpotMarketOrderAuthz) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSpotMarketOrderAuthz.Merge(m, src)
}
func (m *CreateSpotMarketOrderAuthz) XXX_Size() int {
	return m.Size()
}
func (m *CreateSpotMarketOrderAuthz) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSpotMarketOrderAuthz.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSpotMarketOrderAuthz proto.InternalMessageInfo

func (m *CreateSpotMarketOrderAuthz) GetSubaccountId() string {
	if m != nil {
		return m.SubaccountId
	}
	return ""
}

func (m *CreateSpotMarketOrderAuthz) GetMarketIds() []string {
	if m != nil {
		return m.MarketIds
	}
	return nil
}

func (m *CreateSpotMarketOrderAuthz) GetMaxOrderValue() types.Coin {
	if m != nil {
		return m.MaxOrderValue
	}
	return types.Coin{}
}

// CreateDerivativeLimitOrderAuthz defines authorization for creating derivative limit orders
type CreateDerivativeLimitOrderAuthz struct {
	// subaccount_id restricts to specific subaccount (empty = any subaccount)
	SubaccountId string `protobuf:"bytes,1,opt,name=subaccount_id,json=subaccountId,proto3" json:"subaccount_id,omitempty"`
	// market_ids restricts to specific markets (empty = all markets)
	MarketIds []string `protobuf:"bytes,2,rep,name=market_ids,json=marketIds,proto3" json:"market_ids,omitempty"`
	// max_order_value is the maximum value per order (0 = unlimited)
	MaxOrderValue types.Coin `protobuf:"bytes,3,opt,name=max_order_value,json=maxOrderValue,proto3" json:"max_order_value"`
}

func (m *CreateDerivativeLimitOrderAuthz) Reset()         { *m = CreateDerivativeLimitOrderAuthz{} }
func (m *CreateDerivativeLimitOrderAuthz) String() string { return proto.CompactTextString(m) }
func (*CreateDerivativeLimitOrderAuthz) ProtoMessage()    {}
func (*CreateDerivativeLimitOrderAuthz) Descriptor() ([]byte, []int) {
	return fileDescriptor_1520d02852beec97, []int{2}
}
func (m *CreateDerivativeLimitOrderAuthz) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CreateDerivativeLimitOrderAuthz) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CreateDerivativeLimitOrderAuthz.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CreateDerivativeLimitOrderAuthz) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDerivativeLimitOrderAuthz.Merge(m, src)
}
func (m *CreateDerivativeLimitOrderAuthz) XXX_Size() int {
	return m.Size()
}
func (m *CreateDerivativeLimitOrderAuthz) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDerivativeLimitOrderAuthz.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDerivativeLimitOrderAuthz proto.InternalMessageInfo

func (m *CreateDerivativeLimitOrderAuthz) GetSubaccountId() string {
	if m != nil {
		return m.SubaccountId
	}
	return ""
}

func (m *CreateDerivativeLimitOrderAuthz) GetMarketIds() []string {
	if m != nil {
		return m.MarketIds
	}
	return nil
}

func (m *CreateDerivativeLimitOrderAuthz) GetMaxOrderValue() types.Coin {
	if m != nil {
		return m.MaxOrderValue
	}
	return types.Coin{}
}

// CreateDerivativeMarketOrderAuthz defines authorization for creating derivative market orders
type CreateDerivativeMarketOrderAuthz struct {
	// subaccount_id restricts to specific subaccount (empty = any subaccount)
	SubaccountId string `protobuf:"bytes,1,opt,name=subaccount_id,json=subaccountId,proto3" json:"subaccount_id,omitempty"`
	// market_ids restricts to specific markets (empty = all markets)
	MarketIds []string `protobuf:"bytes,2,rep,name=market_ids,json=marketIds,proto3" json:"market_ids,omitempty"`
	// max_order_value is the maximum value per order (0 = unlimited)
	MaxOrderValue types.Coin `protobuf:"bytes,3,opt,name=max_order_value,json=maxOrderValue,proto3" json:"max_order_value"`
}

func (m *CreateDerivativeMarketOrderAuthz) Reset()         { *m = CreateDerivativeMarketOrderAuthz{} }
func (m *CreateDerivativeMarketOrderAuthz) String() string { return proto.CompactTextString(m) }
func (*CreateDerivativeMarketOrderAuthz) ProtoMessage()    {}
func (*CreateDerivativeMarketOrderAuthz) Descriptor() ([]byte, []int) {
	return fileDescriptor_1520d02852beec97, []int{3}
}
func (m *CreateDerivativeMarketOrderAuthz) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CreateDerivativeMarketOrderAuthz) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CreateDerivativeMarketOrderAuthz.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CreateDerivativeMarketOrderAuthz) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDerivativeMarketOrderAuthz.Merge(m, src)
}
func (m *CreateDerivativeMarketOrderAuthz) XXX_Size() int {
	return m.Size()
}
func (m *CreateDerivativeMarketOrderAuthz) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDerivativeMarketOrderAuthz.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDerivativeMarketOrderAuthz proto.InternalMessageInfo

func (m *CreateDerivativeMarketOrderAuthz) GetSubaccountId() string {
	if m != nil {
		return m.SubaccountId
	}
	return ""
}

func (m *CreateDerivativeMarketOrderAuthz) GetMarketIds() []string {
	if m != nil {
		return m.MarketIds
	}
	return nil
}

func (m *CreateDerivativeMarketOrderAuthz) GetMaxOrderValue() types.Coin {
	if m != nil {
		return m.MaxOrderValue
	}
	return types.Coin{}
}

// BatchUpdateOrdersAuthz defines authorization for batch order updates
type BatchUpdateOrdersAuthz struct {
	// subaccount_id restricts to specific subaccount (empty = any subaccount)
	SubaccountId string `protobuf:"bytes,1,opt,name=subaccount_id,json=subaccountId,proto3" json:"subaccount_id,omitempty"`
	// spot_market_ids restricts spot operations to specific markets (empty = all markets)
	SpotMarketIds []string `protobuf:"bytes,2,rep,name=spot_market_ids,json=spotMarketIds,proto3" json:"spot_market_ids,omitempty"`
	// derivative_market_ids restricts derivative operations to specific markets (empty = all markets)
	DerivativeMarketIds []string `protobuf:"bytes,3,rep,name=derivative_market_ids,json=derivativeMarketIds,proto3" json:"derivative_market_ids,omitempty"`
	// max_order_value is the maximum value per individual order (0 = unlimited)
	MaxOrderValue types.Coin `protobuf:"bytes,4,opt,name=max_order_value,json=maxOrderValue,proto3" json:"max_order_value"`
}

func (m *BatchUpdateOrdersAuthz) Reset()         { *m = BatchUpdateOrdersAuthz{} }
func (m *BatchUpdateOrdersAuthz) String() string { return proto.CompactTextString(m) }
func (*BatchUpdateOrdersAuthz) ProtoMessage()    {}
func (*BatchUpdateOrdersAuthz) Descriptor() ([]byte, []int) {
	return fileDescriptor_1520d02852beec97, []int{4}
}
func (m *BatchUpdateOrdersAuthz) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BatchUpdateOrdersAuthz) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BatchUpdateOrdersAuthz.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BatchUpdateOrdersAuthz) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchUpdateOrdersAuthz.Merge(m, src)
}
func (m *BatchUpdateOrdersAuthz) XXX_Size() int {
	return m.Size()
}
func (m *BatchUpdateOrdersAuthz) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchUpdateOrdersAuthz.DiscardUnknown(m)
}

var xxx_messageInfo_BatchUpdateOrdersAuthz proto.InternalMessageInfo

func (m *BatchUpdateOrdersAuthz) GetSubaccountId() string {
	if m != nil {
		return m.SubaccountId
	}
	return ""
}

func (m *BatchUpdateOrdersAuthz) GetSpotMarketIds() []string {
	if m != nil {
		return m.SpotMarketIds
	}
	return nil
}

func (m *BatchUpdateOrdersAuthz) GetDerivativeMarketIds() []string {
	if m != nil {
		return m.DerivativeMarketIds
	}
	return nil
}

func (m *BatchUpdateOrdersAuthz) GetMaxOrderValue() types.Coin {
	if m != nil {
		return m.MaxOrderValue
	}
	return types.Coin{}
}

// CancelSpotOrderAuthz defines authorization for canceling spot orders
type CancelSpotOrderAuthz struct {
	// subaccount_id restricts to specific subaccount (empty = any subaccount)
	SubaccountId string `protobuf:"bytes,1,opt,name=subaccount_id,json=subaccountId,proto3" json:"subaccount_id,omitempty"`
	// market_ids restricts to specific markets (empty = all markets)
	MarketIds []string `protobuf:"bytes,2,rep,name=market_ids,json=marketIds,proto3" json:"market_ids,omitempty"`
}

func (m *CancelSpotOrderAuthz) Reset()         { *m = CancelSpotOrderAuthz{} }
func (m *CancelSpotOrderAuthz) String() string { return proto.CompactTextString(m) }
func (*CancelSpotOrderAuthz) ProtoMessage()    {}
func (*CancelSpotOrderAuthz) Descriptor() ([]byte, []int) {
	return fileDescriptor_1520d02852beec97, []int{5}
}
func (m *CancelSpotOrderAuthz) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CancelSpotOrderAuthz) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CancelSpotOrderAuthz.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CancelSpotOrderAuthz) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelSpotOrderAuthz.Merge(m, src)
}
func (m *CancelSpotOrderAuthz) XXX_Size() int {
	return m.Size()
}
func (m *CancelSpotOrderAuthz) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelSpotOrderAuthz.DiscardUnknown(m)
}

var xxx_messageInfo_CancelSpotOrderAuthz proto.InternalMessageInfo

func (m *CancelSpotOrderAuthz) GetSubaccountId() string {
	if m != nil {
		return m.SubaccountId
	}
	return ""
}

func (m *CancelSpotOrderAuthz) GetMarketIds() []string {
	if m != nil {
		return m.MarketIds
	}
	return nil
}

// CancelDerivativeOrderAuthz defines authorization for canceling derivative orders
type CancelDerivativeOrderAuthz struct {
	// subaccount_id restricts to specific subaccount (empty = any subaccount)
	SubaccountId string `protobuf:"bytes,1,opt,name=subaccount_id,json=subaccountId,proto3" json:"subaccount_id,omitempty"`
	// market_ids restricts to specific markets (empty = all markets)
	MarketIds []string `protobuf:"bytes,2,rep,name=market_ids,json=marketIds,proto3" json:"market_ids,omitempty"`
}

func (m *CancelDerivativeOrderAuthz) Reset()         { *m = CancelDerivativeOrderAuthz{} }
func (m *CancelDerivativeOrderAuthz) String() string { return proto.CompactTextString(m) }
func (*CancelDerivativeOrderAuthz) ProtoMessage()    {}
func (*CancelDerivativeOrderAuthz) Descriptor() ([]byte, []int) {
	return fileDescriptor_1520d02852beec97, []int{6}
}
func (m *CancelDerivativeOrderAuthz) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CancelDerivativeOrderAuthz) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CancelDerivativeOrderAuthz.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CancelDerivativeOrderAuthz) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelDerivativeOrderAuthz.Merge(m, src)
}
func (m *CancelDerivativeOrderAuthz) XXX_Size() int {
	return m.Size()
}
func (m *CancelDerivativeOrderAuthz) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelDerivativeOrderAuthz.DiscardUnknown(m)
}

var xxx_messageInfo_CancelDerivativeOrderAuthz proto.InternalMessageInfo

func (m *CancelDerivativeOrderAuthz) GetSubaccountId() string {
	if m != nil {
		return m.SubaccountId
	}
	return ""
}

func (m *CancelDerivativeOrderAuthz) GetMarketIds() []string {
	if m != nil {
		return m.MarketIds
	}
	return nil
}

// SubaccountTransferAuthz defines authorization for subaccount transfers
type SubaccountTransferAuthz struct {
	// source_subaccount restricts source subaccount (empty = any)
	SourceSubaccount string `protobuf:"bytes,1,opt,name=source_subaccount,json=sourceSubaccount,proto3" json:"source_subaccount,omitempty"`
	// destination_subaccount restricts destination subaccount (empty = any)
	DestinationSubaccount string `protobuf:"bytes,2,opt,name=destination_subaccount,json=destinationSubaccount,proto3" json:"destination_subaccount,omitempty"`
	// max_amount is the maximum transfer amount (0 = unlimited)
	MaxAmount types.Coin `protobuf:"bytes,3,opt,name=max_amount,json=maxAmount,proto3" json:"max_amount"`
}

func (m *SubaccountTransferAuthz) Reset()         { *m = SubaccountTransferAuthz{} }
func (m *SubaccountTransferAuthz) String() string { return proto.CompactTextString(m) }
func (*SubaccountTransferAuthz) ProtoMessage()    {}
func (*SubaccountTransferAuthz) Descriptor() ([]byte, []int) {
	return fileDescriptor_1520d02852beec97, []int{7}
}
func (m *SubaccountTransferAuthz) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SubaccountTransferAuthz) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SubaccountTransferAuthz.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SubaccountTransferAuthz) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubaccountTransferAuthz.Merge(m, src)
}
func (m *SubaccountTransferAuthz) XXX_Size() int {
	return m.Size()
}
func (m *SubaccountTransferAuthz) XXX_DiscardUnknown() {
	xxx_messageInfo_SubaccountTransferAuthz.DiscardUnknown(m)
}

var xxx_messageInfo_SubaccountTransferAuthz proto.InternalMessageInfo

func (m *SubaccountTransferAuthz) GetSourceSubaccount() string {
	if m != nil {
		return m.SourceSubaccount
	}
	return ""
}

func (m *SubaccountTransferAuthz) GetDestinationSubaccount() string {
	if m != nil {
		return m.DestinationSubaccount
	}
	return ""
}

func (m *SubaccountTransferAuthz) GetMaxAmount() types.Coin {
	if m != nil {
		return m.MaxAmount
	}
	return types.Coin{}
}

func init() {
	proto.RegisterType((*CreateSpotLimitOrderAuthz)(nil), "exchange.v1.CreateSpotLimitOrderAuthz")
	proto.RegisterType((*CreateSpotMarketOrderAuthz)(nil), "exchange.v1.CreateSpotMarketOrderAuthz")
	proto.RegisterType((*CreateDerivativeLimitOrderAuthz)(nil), "exchange.v1.CreateDerivativeLimitOrderAuthz")
	proto.RegisterType((*CreateDerivativeMarketOrderAuthz)(nil), "exchange.v1.CreateDerivativeMarketOrderAuthz")
	proto.RegisterType((*BatchUpdateOrdersAuthz)(nil), "exchange.v1.BatchUpdateOrdersAuthz")
	proto.RegisterType((*CancelSpotOrderAuthz)(nil), "exchange.v1.CancelSpotOrderAuthz")
	proto.RegisterType((*CancelDerivativeOrderAuthz)(nil), "exchange.v1.CancelDerivativeOrderAuthz")
	proto.RegisterType((*SubaccountTransferAuthz)(nil), "exchange.v1.SubaccountTransferAuthz")
}

func init() { proto.RegisterFile("exchange/v1/authz.proto", fileDescriptor_1520d02852beec97) }

var fileDescriptor_1520d02852beec97 = []byte{
	// 636 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x96, 0x4f, 0x4f, 0xd4, 0x4e,
	0x18, 0xc7, 0xb7, 0x0b, 0xf9, 0x25, 0x3b, 0xfc, 0x08, 0xb2, 0xf2, 0x3f, 0xa1, 0x6c, 0x4a, 0x62,
	0x56, 0x0d, 0x6d, 0xc0, 0x78, 0xe1, 0x60, 0x02, 0x68, 0x14, 0x15, 0x4d, 0x00, 0x3d, 0x78, 0x69,
	0x66, 0xa7, 0x8f, 0xbb, 0xa3, 0xdb, 0x99, 0xa6, 0x33, 0x5b, 0x2b, 0x57, 0xe3, 0x85, 0x93, 0x2f,
	0xc2, 0xb3, 0xe1, 0xe0, 0x8b, 0x20, 0x9e, 0x38, 0x7a, 0x32, 0x06, 0x0e, 0xbe, 0x04, 0xe3, 0xcd,
	0xcc, 0xb4, 0xb4, 0x9b, 0x85, 0x26, 0x95, 0x70, 0xe0, 0xb2, 0xd9, 0xce, 0xf7, 0x79, 0x76, 0x3e,
	0xdf, 0xef, 0x3c, 0x9d, 0x2c, 0x9a, 0x86, 0x98, 0x74, 0x30, 0x6b, 0x83, 0x13, 0x2d, 0x3b, 0xb8,
	0x27, 0x3b, 0x7b, 0x76, 0x10, 0x72, 0xc9, 0xeb, 0x23, 0xa7, 0x82, 0x1d, 0x2d, 0xcf, 0x8d, 0x63,
	0x9f, 0x32, 0xee, 0xe8, 0xcf, 0x44, 0x9f, 0x9b, 0x25, 0x5c, 0xf8, 0x5c, 0xb8, 0xfa, 0xc9, 0x49,
	0x1e, 0x52, 0x69, 0xa2, 0xcd, 0xdb, 0x3c, 0x59, 0x57, 0xdf, 0xd2, 0x55, 0x33, 0xa9, 0x71, 0x5a,
	0x58, 0xa8, 0xcd, 0x5a, 0x20, 0xf1, 0xb2, 0x43, 0x38, 0x65, 0x89, 0x6e, 0xfd, 0x36, 0xd0, 0xec,
	0x46, 0x08, 0x58, 0xc2, 0x4e, 0xc0, 0xe5, 0x53, 0xea, 0x53, 0xf9, 0x3c, 0xf4, 0x20, 0x5c, 0x53,
	0x50, 0xf5, 0x45, 0x34, 0x2a, 0x7a, 0x2d, 0x4c, 0x08, 0xef, 0x31, 0xe9, 0x52, 0x6f, 0xc6, 0x68,
	0x18, 0xcd, 0xda, 0xf6, 0xff, 0xf9, 0xe2, 0xa6, 0x57, 0x9f, 0x47, 0xc8, 0xc7, 0xe1, 0x5b, 0x50,
	0x05, 0x62, 0xa6, 0xda, 0x18, 0x6a, 0xd6, 0xb6, 0x6b, 0xc9, 0xca, 0xa6, 0x27, 0xea, 0x0f, 0xd1,
	0x98, 0x8f, 0x63, 0x97, 0xab, 0x5f, 0x75, 0x23, 0xdc, 0xed, 0xc1, 0xcc, 0x50, 0xc3, 0x68, 0x8e,
	0xac, 0xcc, 0xda, 0x29, 0xbf, 0x62, 0xb3, 0x53, 0x36, 0x7b, 0x83, 0x53, 0xb6, 0x3e, 0x7c, 0xf8,
	0x63, 0xa1, 0xb2, 0x3d, 0xea, 0xe3, 0x58, 0xc3, 0xbc, 0x54, 0x5d, 0xab, 0x5b, 0xdf, 0xbe, 0x2e,
	0x59, 0x69, 0x4b, 0x92, 0xd9, 0x69, 0x8f, 0x82, 0xe5, 0x21, 0xdd, 0xc3, 0x92, 0x72, 0xb6, 0xff,
	0xeb, 0xe0, 0x96, 0x95, 0xe5, 0x5b, 0xe8, 0xcd, 0xfa, 0x63, 0xa0, 0xb9, 0x5c, 0xdd, 0xd2, 0xbc,
	0x57, 0xd5, 0xfa, 0xb3, 0xf2, 0xd6, 0x17, 0xcf, 0xb1, 0x3e, 0x68, 0xce, 0xfa, 0x50, 0x45, 0x0b,
	0x89, 0x7c, 0x1f, 0x42, 0x1a, 0x61, 0x49, 0x23, 0xb8, 0xd2, 0x67, 0xbf, 0x53, 0x3e, 0x80, 0xe6,
	0x40, 0x00, 0x85, 0x0e, 0xad, 0x8f, 0x55, 0xd4, 0x18, 0xac, 0xb9, 0xda, 0x73, 0xb0, 0x5b, 0x3e,
	0x86, 0x9b, 0x85, 0x31, 0x9c, 0x99, 0x86, 0x2f, 0x55, 0x34, 0xb5, 0x8e, 0x25, 0xe9, 0xbc, 0x08,
	0x3c, 0x2c, 0x41, 0x2b, 0xe2, 0x1f, 0xdc, 0xdf, 0x40, 0x63, 0x22, 0xe0, 0xd2, 0x3d, 0x13, 0xc1,
	0xa8, 0xc8, 0x86, 0x4f, 0xc5, 0xb0, 0x82, 0x26, 0xbd, 0x8c, 0xa2, 0xbf, 0x7a, 0x48, 0x57, 0x5f,
	0xf7, 0x06, 0x10, 0x0b, 0xa2, 0x1b, 0xbe, 0x50, 0x74, 0x8f, 0xcb, 0x47, 0xb7, 0x90, 0x45, 0x77,
	0x7e, 0x2a, 0xd6, 0x67, 0x03, 0x4d, 0x6c, 0x60, 0x46, 0xa0, 0xab, 0xde, 0xae, 0xcb, 0x1d, 0x96,
	0xd5, 0x47, 0xe5, 0x41, 0xe7, 0xf3, 0x33, 0x3e, 0x87, 0xc6, 0x3a, 0x50, 0x37, 0x9c, 0x16, 0xf2,
	0xc3, 0xbf, 0x64, 0xd8, 0x8b, 0x5d, 0x4c, 0x85, 0x4c, 0xd6, 0x7e, 0x15, 0x4d, 0xef, 0x64, 0xfb,
	0xef, 0x86, 0x98, 0x89, 0xd7, 0xa7, 0xbc, 0xb7, 0xd1, 0xb8, 0xe0, 0xbd, 0x90, 0x80, 0x9b, 0x13,
	0xa6, 0xcc, 0xd7, 0x12, 0x21, 0xef, 0xac, 0xdf, 0x45, 0x53, 0x1e, 0x08, 0x49, 0x99, 0xde, 0xbf,
	0xbf, 0xa3, 0xaa, 0x3b, 0x26, 0xfb, 0xd4, 0xbe, 0xb6, 0x7b, 0xca, 0x6e, 0xec, 0x62, 0x5f, 0x97,
	0x96, 0x7c, 0x49, 0x6b, 0x3e, 0x8e, 0xd7, 0x74, 0xc7, 0xea, 0x93, 0xf2, 0x79, 0x34, 0xb2, 0x3c,
	0x0a, 0x0c, 0xaf, 0xbb, 0x87, 0xc7, 0xa6, 0x71, 0x74, 0x6c, 0x1a, 0x3f, 0x8f, 0x4d, 0xe3, 0xd3,
	0x89, 0x59, 0x39, 0x3a, 0x31, 0x2b, 0xdf, 0x4f, 0xcc, 0xca, 0xab, 0x07, 0x84, 0x7b, 0x60, 0xef,
	0x01, 0x44, 0x60, 0x33, 0x90, 0x0e, 0xe9, 0x52, 0x60, 0x72, 0x29, 0x08, 0xf9, 0x1b, 0x20, 0x52,
	0x38, 0x24, 0xe4, 0x8c, 0x8b, 0xa5, 0x77, 0x1d, 0x2a, 0xa1, 0x8b, 0x5b, 0xd0, 0xed, 0x52, 0xd6,
	0x76, 0x62, 0x27, 0xdb, 0x52, 0xbe, 0x0f, 0x40, 0xb4, 0xfe, 0xd3, 0xff, 0x01, 0xee, 0xfc, 0x0d,
	0x00, 0x00, 0xff, 0xff, 0x29, 0x8e, 0x1b, 0xac, 0x8f, 0x08, 0x00, 0x00,
}

func (m *CreateSpotLimitOrderAuthz) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreateSpotLimitOrderAuthz) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CreateSpotLimitOrderAuthz) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.MaxOrderValue.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintAuthz(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.MarketIds) > 0 {
		for iNdEx := len(m.MarketIds) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.MarketIds[iNdEx])
			copy(dAtA[i:], m.MarketIds[iNdEx])
			i = encodeVarintAuthz(dAtA, i, uint64(len(m.MarketIds[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.SubaccountId) > 0 {
		i -= len(m.SubaccountId)
		copy(dAtA[i:], m.SubaccountId)
		i = encodeVarintAuthz(dAtA, i, uint64(len(m.SubaccountId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CreateSpotMarketOrderAuthz) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreateSpotMarketOrderAuthz) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CreateSpotMarketOrderAuthz) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.MaxOrderValue.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintAuthz(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.MarketIds) > 0 {
		for iNdEx := len(m.MarketIds) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.MarketIds[iNdEx])
			copy(dAtA[i:], m.MarketIds[iNdEx])
			i = encodeVarintAuthz(dAtA, i, uint64(len(m.MarketIds[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.SubaccountId) > 0 {
		i -= len(m.SubaccountId)
		copy(dAtA[i:], m.SubaccountId)
		i = encodeVarintAuthz(dAtA, i, uint64(len(m.SubaccountId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CreateDerivativeLimitOrderAuthz) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreateDerivativeLimitOrderAuthz) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CreateDerivativeLimitOrderAuthz) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.MaxOrderValue.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintAuthz(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.MarketIds) > 0 {
		for iNdEx := len(m.MarketIds) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.MarketIds[iNdEx])
			copy(dAtA[i:], m.MarketIds[iNdEx])
			i = encodeVarintAuthz(dAtA, i, uint64(len(m.MarketIds[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.SubaccountId) > 0 {
		i -= len(m.SubaccountId)
		copy(dAtA[i:], m.SubaccountId)
		i = encodeVarintAuthz(dAtA, i, uint64(len(m.SubaccountId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CreateDerivativeMarketOrderAuthz) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreateDerivativeMarketOrderAuthz) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CreateDerivativeMarketOrderAuthz) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.MaxOrderValue.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintAuthz(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.MarketIds) > 0 {
		for iNdEx := len(m.MarketIds) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.MarketIds[iNdEx])
			copy(dAtA[i:], m.MarketIds[iNdEx])
			i = encodeVarintAuthz(dAtA, i, uint64(len(m.MarketIds[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.SubaccountId) > 0 {
		i -= len(m.SubaccountId)
		copy(dAtA[i:], m.SubaccountId)
		i = encodeVarintAuthz(dAtA, i, uint64(len(m.SubaccountId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *BatchUpdateOrdersAuthz) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BatchUpdateOrdersAuthz) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BatchUpdateOrdersAuthz) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.MaxOrderValue.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintAuthz(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.DerivativeMarketIds) > 0 {
		for iNdEx := len(m.DerivativeMarketIds) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.DerivativeMarketIds[iNdEx])
			copy(dAtA[i:], m.DerivativeMarketIds[iNdEx])
			i = encodeVarintAuthz(dAtA, i, uint64(len(m.DerivativeMarketIds[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.SpotMarketIds) > 0 {
		for iNdEx := len(m.SpotMarketIds) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.SpotMarketIds[iNdEx])
			copy(dAtA[i:], m.SpotMarketIds[iNdEx])
			i = encodeVarintAuthz(dAtA, i, uint64(len(m.SpotMarketIds[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.SubaccountId) > 0 {
		i -= len(m.SubaccountId)
		copy(dAtA[i:], m.SubaccountId)
		i = encodeVarintAuthz(dAtA, i, uint64(len(m.SubaccountId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CancelSpotOrderAuthz) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CancelSpotOrderAuthz) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CancelSpotOrderAuthz) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MarketIds) > 0 {
		for iNdEx := len(m.MarketIds) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.MarketIds[iNdEx])
			copy(dAtA[i:], m.MarketIds[iNdEx])
			i = encodeVarintAuthz(dAtA, i, uint64(len(m.MarketIds[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.SubaccountId) > 0 {
		i -= len(m.SubaccountId)
		copy(dAtA[i:], m.SubaccountId)
		i = encodeVarintAuthz(dAtA, i, uint64(len(m.SubaccountId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CancelDerivativeOrderAuthz) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CancelDerivativeOrderAuthz) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CancelDerivativeOrderAuthz) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MarketIds) > 0 {
		for iNdEx := len(m.MarketIds) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.MarketIds[iNdEx])
			copy(dAtA[i:], m.MarketIds[iNdEx])
			i = encodeVarintAuthz(dAtA, i, uint64(len(m.MarketIds[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.SubaccountId) > 0 {
		i -= len(m.SubaccountId)
		copy(dAtA[i:], m.SubaccountId)
		i = encodeVarintAuthz(dAtA, i, uint64(len(m.SubaccountId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SubaccountTransferAuthz) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SubaccountTransferAuthz) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SubaccountTransferAuthz) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.MaxAmount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintAuthz(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.DestinationSubaccount) > 0 {
		i -= len(m.DestinationSubaccount)
		copy(dAtA[i:], m.DestinationSubaccount)
		i = encodeVarintAuthz(dAtA, i, uint64(len(m.DestinationSubaccount)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.SourceSubaccount) > 0 {
		i -= len(m.SourceSubaccount)
		copy(dAtA[i:], m.SourceSubaccount)
		i = encodeVarintAuthz(dAtA, i, uint64(len(m.SourceSubaccount)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintAuthz(dAtA []byte, offset int, v uint64) int {
	offset -= sovAuthz(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *CreateSpotLimitOrderAuthz) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SubaccountId)
	if l > 0 {
		n += 1 + l + sovAuthz(uint64(l))
	}
	if len(m.MarketIds) > 0 {
		for _, s := range m.MarketIds {
			l = len(s)
			n += 1 + l + sovAuthz(uint64(l))
		}
	}
	l = m.MaxOrderValue.Size()
	n += 1 + l + sovAuthz(uint64(l))
	return n
}

func (m *CreateSpotMarketOrderAuthz) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SubaccountId)
	if l > 0 {
		n += 1 + l + sovAuthz(uint64(l))
	}
	if len(m.MarketIds) > 0 {
		for _, s := range m.MarketIds {
			l = len(s)
			n += 1 + l + sovAuthz(uint64(l))
		}
	}
	l = m.MaxOrderValue.Size()
	n += 1 + l + sovAuthz(uint64(l))
	return n
}

func (m *CreateDerivativeLimitOrderAuthz) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SubaccountId)
	if l > 0 {
		n += 1 + l + sovAuthz(uint64(l))
	}
	if len(m.MarketIds) > 0 {
		for _, s := range m.MarketIds {
			l = len(s)
			n += 1 + l + sovAuthz(uint64(l))
		}
	}
	l = m.MaxOrderValue.Size()
	n += 1 + l + sovAuthz(uint64(l))
	return n
}

func (m *CreateDerivativeMarketOrderAuthz) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SubaccountId)
	if l > 0 {
		n += 1 + l + sovAuthz(uint64(l))
	}
	if len(m.MarketIds) > 0 {
		for _, s := range m.MarketIds {
			l = len(s)
			n += 1 + l + sovAuthz(uint64(l))
		}
	}
	l = m.MaxOrderValue.Size()
	n += 1 + l + sovAuthz(uint64(l))
	return n
}

func (m *BatchUpdateOrdersAuthz) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SubaccountId)
	if l > 0 {
		n += 1 + l + sovAuthz(uint64(l))
	}
	if len(m.SpotMarketIds) > 0 {
		for _, s := range m.SpotMarketIds {
			l = len(s)
			n += 1 + l + sovAuthz(uint64(l))
		}
	}
	if len(m.DerivativeMarketIds) > 0 {
		for _, s := range m.DerivativeMarketIds {
			l = len(s)
			n += 1 + l + sovAuthz(uint64(l))
		}
	}
	l = m.MaxOrderValue.Size()
	n += 1 + l + sovAuthz(uint64(l))
	return n
}

func (m *CancelSpotOrderAuthz) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SubaccountId)
	if l > 0 {
		n += 1 + l + sovAuthz(uint64(l))
	}
	if len(m.MarketIds) > 0 {
		for _, s := range m.MarketIds {
			l = len(s)
			n += 1 + l + sovAuthz(uint64(l))
		}
	}
	return n
}

func (m *CancelDerivativeOrderAuthz) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SubaccountId)
	if l > 0 {
		n += 1 + l + sovAuthz(uint64(l))
	}
	if len(m.MarketIds) > 0 {
		for _, s := range m.MarketIds {
			l = len(s)
			n += 1 + l + sovAuthz(uint64(l))
		}
	}
	return n
}

func (m *SubaccountTransferAuthz) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SourceSubaccount)
	if l > 0 {
		n += 1 + l + sovAuthz(uint64(l))
	}
	l = len(m.DestinationSubaccount)
	if l > 0 {
		n += 1 + l + sovAuthz(uint64(l))
	}
	l = m.MaxAmount.Size()
	n += 1 + l + sovAuthz(uint64(l))
	return n
}

func sovAuthz(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAuthz(x uint64) (n int) {
	return sovAuthz(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *CreateSpotLimitOrderAuthz) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAuthz
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreateSpotLimitOrderAuthz: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreateSpotLimitOrderAuthz: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubaccountId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthz
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthz
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SubaccountId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MarketIds", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthz
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthz
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MarketIds = append(m.MarketIds, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxOrderValue", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAuthz
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAuthz
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaxOrderValue.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAuthz(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAuthz
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CreateSpotMarketOrderAuthz) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAuthz
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreateSpotMarketOrderAuthz: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreateSpotMarketOrderAuthz: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubaccountId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthz
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthz
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SubaccountId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MarketIds", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthz
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthz
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MarketIds = append(m.MarketIds, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxOrderValue", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAuthz
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAuthz
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaxOrderValue.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAuthz(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAuthz
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CreateDerivativeLimitOrderAuthz) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAuthz
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreateDerivativeLimitOrderAuthz: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreateDerivativeLimitOrderAuthz: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubaccountId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthz
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthz
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SubaccountId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MarketIds", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthz
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthz
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MarketIds = append(m.MarketIds, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxOrderValue", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAuthz
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAuthz
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaxOrderValue.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAuthz(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAuthz
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CreateDerivativeMarketOrderAuthz) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAuthz
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreateDerivativeMarketOrderAuthz: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreateDerivativeMarketOrderAuthz: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubaccountId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthz
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthz
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SubaccountId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MarketIds", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthz
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthz
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MarketIds = append(m.MarketIds, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxOrderValue", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAuthz
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAuthz
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaxOrderValue.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAuthz(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAuthz
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BatchUpdateOrdersAuthz) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAuthz
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BatchUpdateOrdersAuthz: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BatchUpdateOrdersAuthz: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubaccountId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthz
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthz
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SubaccountId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SpotMarketIds", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthz
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthz
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SpotMarketIds = append(m.SpotMarketIds, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DerivativeMarketIds", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthz
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthz
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DerivativeMarketIds = append(m.DerivativeMarketIds, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxOrderValue", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAuthz
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAuthz
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaxOrderValue.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAuthz(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAuthz
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CancelSpotOrderAuthz) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAuthz
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CancelSpotOrderAuthz: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CancelSpotOrderAuthz: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubaccountId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthz
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthz
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SubaccountId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MarketIds", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthz
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthz
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MarketIds = append(m.MarketIds, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAuthz(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAuthz
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CancelDerivativeOrderAuthz) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAuthz
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CancelDerivativeOrderAuthz: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CancelDerivativeOrderAuthz: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubaccountId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthz
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthz
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SubaccountId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MarketIds", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthz
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthz
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MarketIds = append(m.MarketIds, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAuthz(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAuthz
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SubaccountTransferAuthz) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAuthz
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SubaccountTransferAuthz: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SubaccountTransferAuthz: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceSubaccount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthz
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthz
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourceSubaccount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DestinationSubaccount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthz
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthz
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DestinationSubaccount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAuthz
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAuthz
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaxAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAuthz(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAuthz
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAuthz(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAuthz
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAuthz
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAuthz
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAuthz
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAuthz        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAuthz          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAuthz = fmt.Errorf("proto: unexpected end of group")
)
